Added security CI workflow and OS build qualifier
opensearch-project/cross-cluster-replication pull request #358
Opened 2022-04-06 13:24 UTC by saikaranam-amazon

Signed-off-by: Sai Kumar <karanas@amazon.com>

### Description
Added security CI workflow and OS build qualifier
 
### Issues Resolved

 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2022-04-06 18:14 UTC, peterzhuamazon requested changes
build.gradle 83-86 should change to
`version = "${opensearch_build}"

2022-04-07 15:47 UTC, saikaranam-amazon commented on .github/workflows/security-tests.yml
> +          cp build/distributions/opensearch-security-*.zip ../src/test/resources/security/plugin/opensearch-security.zip
Tracked here: https://github.com/opensearch-project/cross-cluster-replication/issues/274

2022-04-07 15:48 UTC, saikaranam-amazon commented
> build.gradle 83-86 should change to
version = "${opensearch_build}"

Done

2022-04-07 16:06 UTC, naveenpajjuri approved these changes

2022-04-07 16:10 UTC, ankitkala approved these changes
LGTM.

2022-04-07 17:20 UTC, merged