Integration test for cluster reroute in
opensearch-project/cross-cluster-replication pull request #81
Opened 2021-08-03 11:33 UTC by tbhanu-amzn

### Description
Integration test for cluster reroute case
 
### Check List
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2021-08-24 12:50 UTC, tbhanu-amzn commented on src/test/kotlin/com/amazon/elasticsearch/replication/MultiClusterRestTestCase.kt
> +        val persistentConnectionRequest = Request("GET", "/_cat/shards")
done

2021-08-24 12:51 UTC, tbhanu-amzn commented on src/test/kotlin/com/amazon/elasticsearch/replication/MultiClusterRestTestCase.kt
> +        val persistentConnectionRequest = Request("GET", "/_cat/nodes")
done

2021-08-24 12:51 UTC, tbhanu-amzn commented on src/test/kotlin/com/amazon/elasticsearch/replication/integ/rest/ClusterRerouteFollowerIT.kt
> +}
done

2021-08-24 12:52 UTC, tbhanu-amzn commented on src/test/kotlin/com/amazon/elasticsearch/replication/integ/rest/ClusterRerouteFollowerIT.kt
> +            }, 1, TimeUnit.MINUTES)
done

2021-08-24 12:53 UTC, tbhanu-amzn commented on src/test/kotlin/com/amazon/elasticsearch/replication/integ/rest/ClusterRerouteFollowerIT.kt
> +            }, 1, TimeUnit.MINUTES)*/
this is solved in the pr https://github.com/opensearch-project/cross-cluster-replication/pull/114

2021-09-01 08:11 UTC, krishna-ggk requested changes
Should we drop this since these are covered in diff PR?

2021-09-02 05:11 UTC, tbhanu-amzn commented
This is already addressed in #114

2021-09-02 05:11 UTC, closed without merging